version: "3" # composeファイルのバージョン
services:
  app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    # M1チップの場合コメント外す
    # platform: 'linux/amd64'
    container_name: app
    # コンテナの永続化
    tty: true
    # ホストPCとコンテナ内とのデータの同期
    volumes:
      - ./backend:/app/
    ports:
      - 18080:8080
    depends_on:
      - db
    # 開発環境の起動
    command: "air -c backend/.air.toml"

  db: # qin-memo-backendのやつを参考にする
    image: mysql:5.7 # mysql:8.0でもいいかも
    # M1チップの場合コメント外す
    # platform: 'linux/amd64'
    container_name: mysql
    # コンテナの永続化
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: qin-todo
      # TZ: "Asia/Tokyo" # とりあえず、タイムゾーンは設定しないようにする
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #mysqlで日本語を使うようにする設定だと思う。
    # mysqlのデータをホストPCに同期（コンテナが消えてしまってもホストPCにデータが残る）
    volumes:
      - ./docker/mysql/mysql_data:/var/lib/mysql #テーブルデータ
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf #設定データ
      # - ./docker/db/sql:/docker-entrypoint-initdb.d #何かわからん。dbの初期化に関係してそう。とりあえず、コメント化しておく
    ports:
      - 13306:3306

  redis:
    image: "redis:6.2.6"
    container_name: redis
    ports:
      - "16379:6379"
    # いまのところ使う必要なさそうなため、コメントアウトしておく
    # volumes:
      # - "./tools/docker/db/redis.conf:/usr/local/etc/redis/redis.conf"
      # - "./tools/docker/db/redis_data:/data"
    # command: "redis-server /usr/local/etc/redis/redis.conf"
