FROM golang:1.18.1

WORKDIR /app

COPY go.* ./

RUN go mod download

# DBマイグレーションツールのインストール
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Golang ホットリロードするためインストールする
RUN go get -u github.com/cosmtrek/air

# gitをインストール(vscodeの拡張機能「remote - Containers」を使って開発する場合)
# RUN apt-get install git

# Goの拡張機能のインストール
# vscode上でもインストールできるから書かなくてもいいかも
# RUN go install -v golang.org/x/tools/gopls@latest
# RUN go install -v github.com/ramya-rao-a/go-outline@latest

COPY . ./
