version: "3" # composeファイルのバージョン
services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    # M1チップの場合コメント外す
    # platform: 'linux/amd64'
    container_name: app
    # コンテナの永続化
    tty: true
    # ホストPCとコンテナ内とのデータの同期
    volumes:
      - ./cmd:/app/cmd
      - ./tools/database:/app/tools/database
    ports:
      - 18080:8080
    depends_on:
      - db
    # 開発環境の起動
    command: air

  db: # qin-memo-backendのやつを参考にする
    image: mysql:5.7 # mysql:8.0でもいいかも
    # M1チップの場合コメント外す
    # platform: 'linux/amd64'
    container_name: mysql
    # コンテナの永続化
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: qin-todo
      # TZ: "Asia/Tokyo" # とりあえず、タイムゾーンは設定しないようにする
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #mysqlで日本語を使うようにする設定だと思う。
    # mysqlのデータをホストPCに同期（コンテナが消えてしまってもホストPCにデータが残る）
    volumes:
      - ./tools/docker/db/mysql_data:/var/lib/mysql #テーブルデータ
      - ./tools/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf #設定データ
      # - ./docker/db/sql:/docker-entrypoint-initdb.d #何かわからん。dbの初期化に関係してそう。とりあえず、コメント化しておく
    ports:
      - 13306:3306

  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/qin-todo.yaml'
    volumes:
      - ./api/qin-todo.yaml:/tmp/qin-todo.yaml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - '18081:4010'
