name: OpenAPI generate to html deploy for GCS

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ["14"]
    steps:
      - name: checkout
        uses: actions/checkout@v3 # これでレポジトリからコードを取得できるけど、なんでか分からん

      - name: node setting
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install redoc
        run: npm install -g redoc-cli

      - name: build OpenAPI file
        run: redoc-cli bundle ./docs/openapi.yaml

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./redoc-static.html
          destination: qin-todo-team-l-openapi
