# ワークフローの名前　ワークフローの名前を name で指定できる（省略可）
name: Action Sample

# トリガーイベント　ワークフローを実行するための条件を on 以下に指定する（複数の条件を指定可能）　トリガーイベントとして、プルリクエストや特定のタグ、cronなども指定可能
on:
  push:
    branches:
      - master # このワークフローはサンプル用であるため、存在しないブランチを指定して実行させないようにする
  workflow_dispatch:  #GitHub上で手動実行

# 実行する処理内容や実行環境をjobs以降に記述する。なお、1つのYAMLファイルに複数のジョブを指定可能。原則として各ジョブは並列に実行されるが、依存関係（他のジョブの終了を待つ）を設定することも可能。
jobs:
  print-hello-world:  # ジョブ名　ジョブ名には英数字と-, _のみ使用可（スペースは使用不可）
    runs-on: ubuntu-latest  # ジョブが実行されるマシンの種類
    # steps以降に実行する処理（タスク）を記述
    steps:
      - name: execute echo command  # タスクの名前（省略可）
        run: echo "Hello World!"
